---
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todos":
    post:
      summary: Creates a todo
      tags:
      - Todos
      security:
      - bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: todo created
          content: {}
        '401':
          description: authentication failed
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
servers:
- url: http://localhost:3000/
  variables:
    defaultHost:
      default: www.example.com
